Disable scheduled jobs for forks
mattermost/actions-workflows pull request #37
Opened 2023-11-17 17:21 UTC by mickmister

#### Summary

There is a long-running issue where forked plugin repos are running scheduled jobs every day, since each plugin repo's workflow is currently configured to do so. More info here:
https://mattermost.atlassian.net/browse/MM-52947?focusedCommentId=158170
https://github.com/mattermost/mattermost-plugin-starter-template/pull/189#issuecomment-1781855089

At the moment, the PR keeps the scheduled jobs running in the Mattermost org. We could alternatively just not run the scheduled jobs on the Mattermost org either. We currently don't have a mechanism set up to be notified of these scheduled jobs failing, so maybe it makes sense to disable them until that is the case, but 0/5 on this

2023-11-23 07:59 UTC, hanzei requested changes
Should we make this configurable (and off by default)?

For projects like Matterpoll I quite like the nightly builds as they give an early warning when something is off with the pipeline.

2024-02-23 04:05 UTC, mickmister commented
@hanzei I tested this with a forked repo with the following logic:

- On my forked repo, set cron schedule to "every 5 minutes" for testing
  - Observe that the scheduled workflow runs
- Introduce `run-scheduled` param to centralized action workflow, as done in this PR
  - Observe that the scheduled workflow is "skipped"
- Use the `run-scheduled` parameter in the forked repo's workflow https://github.com/mickmister/mattermost-plugin-example-oauth-provider/blob/7c8e9966bd15e87599d1e3d566484ffdee53e2dc/.github/workflows/ci.yml#L21
  - Observe the scheduled workflow runs


https://github.com/mickmister/mattermost-plugin-example-oauth-provider/actions

![image](https://github.com/mattermost/actions-workflows/assets/6913320/5f99fdeb-57c1-4325-826e-bf9ee27485e6)

2024-02-28 13:40 UTC, hanzei approved these changes
LGTM :+1:

2024-02-29 14:34 UTC, toninis approved these changes

2024-02-29 14:36 UTC, merged